spring.application.name=BookMarked

spring.datasource.url=jdbc:mysql://localhost:3306/bookmarked
spring.datasource.username=root
spring.datasource.password=Samsung@24
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Base64-encoded 256-bit key for HS256
app.jwt.secret=V0VfQk9PS01BUktfU0VDVVJJVFlfS0VZXzI1Nl9CSVRTX0JBU0U2NF9TVFJJTkc=
app.jwt.expiration-ms=86400000